# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: generate animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * * " # every 0 hours

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: sunsgneayo
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: main
          author: sunsgne <sunsgneant@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
